version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - target/SampleMavenTomcatApp.war
    - appspec.yml
  discard-paths: yes
  #  - '**/*'
