version: 0.0
os: linux
phases:
  build:
    commands:
      - echo Build completed on `date`
      - sudo mvn package

artifacts:
  files:
    - target/SampleMavenTomcatApp.war
    - appspec.yml
  discard-paths: yes
  #  - '**/*'
